### ISSUE TITLE
PHP7 does not compile on arm64

### ISSUE THREAD

**Issue by oparoz** [kyrofa/owncloud-snap#64]
```
/bin/bash /build/owncloud-lamp-snap/parts/php/build/libtool --silent --preserve-dup-deps --mode=compile cc  -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/build/owncloud-lamp-snap/parts/php/build/Zend/ -DPHP_ATOM_INC -I/build/owncloud-lamp-snap/parts/php/build/include -I/build/owncloud-lamp-snap/parts/php/build/main -I/build/owncloud-lamp-snap/parts/php/build -I/build/owncloud-lamp-snap/parts/php/build/ext/date/lib -I/usr/include/libxml2 -I/usr/include/freetype2 -I/build/owncloud-lamp-snap/parts/php/build/ext/mbstring/oniguruma -I/build/owncloud-lamp-snap/parts/php/build/ext/mbstring/libmbfl -I/build/owncloud-lamp-snap/parts/php/build/ext/mbstring/libmbfl/mbfl -I/build/owncloud-lamp-snap/parts/php/build/ext/sqlite3/libsqlite -I/build/owncloud-lamp-snap/parts/php/build/ext/zip/lib -I/build/owncloud-lamp-snap/parts/php/build/TSRM -I/build/owncloud-lamp-snap/parts/php/build/Zend  -I/build/owncloud-lamp-snap/stage/include  -I/usr/include -I/build/owncloud-lamp-snap/stage/include -fvisibility=hidden   -c /build/owncloud-lamp-snap/parts/php/build/Zend/zend_API.c -o Zend/zend_API.lo 
/tmp/ccTLERii.s: Assembler messages:
/tmp/ccTLERii.s:7260: Error: operand 2 should be an integer register -- `mul x1,[x29,96],[x29,104]'
/tmp/ccTLERii.s:7261: Error: operand 2 should be an integer register -- `smulh x0,[x29,96],[x29,104]'
/tmp/ccTLERii.s:7310: Error: operand 2 should be an integer register -- `mul x1,[x29,104],[x29,104]'
/tmp/ccTLERii.s:7311: Error: operand 2 should be an integer register -- `smulh x0,[x29,104],[x29,104]'
/bin/bash /build/owncloud-lamp-snap/parts/php/build/libtool --silent --preserve-dup-deps --mode=compile cc  -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -IZend/ -I/build/owncloud-lamp-snap/parts/php/build/Zend/ -DPHP_ATOM_INC -I/build/owncloud-lamp-snap/parts/php/build/include -I/build/owncloud-lamp-snap/parts/php/build/main -I/build/owncloud-lamp-snap/parts/php/build -I/build/owncloud-lamp-snap/parts/php/build/ext/date/lib -I/usr/include/libxml2 -I/usr/include/freetype2 -I/build/owncloud-lamp-snap/parts/php/build/ext/mbstring/oniguruma -I/build/owncloud-lamp-snap/parts/php/build/ext/mbstring/libmbfl -I/build/owncloud-lamp-snap/parts/php/build/ext/mbstring/libmbfl/mbfl -I/build/owncloud-lamp-snap/parts/php/build/ext/sqlite3/libsqlite -I/build/owncloud-lamp-snap/parts/php/build/ext/zip/lib -I/build/owncloud-lamp-snap/parts/php/build/TSRM -I/build/owncloud-lamp-snap/parts/php/build/Zend  -I/build/owncloud-lamp-snap/stage/include  -I/usr/include -I/build/owncloud-lamp-snap/stage/include -fvisibility=hidden   -c /build/owncloud-lamp-snap/parts/php/build/Zend/zend_extensions.c -o Zend/zend_extensions.lo 
Makefile:1872: recipe for target 'Zend/zend_operators.lo' failed
make: *** [Zend/zend_operators.lo] Error 1
make: *** Waiting for unfinished jobs....
Command '['/bin/sh', '/tmp/tmp055h8wil', 'make', '-j4']' returned non-
zero exit status 2
Traceback (most recent call last):
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 195, in main
    builder.build()
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 141, in build
    ["snapcraft"], path=os.path.join("/build", self.name))
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 92, in run_build_command
    self.chroot(["/bin/sh", "-c", command], echo=echo)
  File "/usr/share/launchpad-buildd/slavebin/buildsnap", line 66, in chroot
    "/usr/bin/sudo", "/usr/sbin/chroot", self.chroot_path] + args)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['/usr/bin/sudo', '/usr/sbin/chroot', '/home/buildd/build-SNAPBUILD-719/chroot-autobuild', 'linux64', '/bin/sh', '-c', 'cd /build/owncloud-lamp-snap && env LANG=C.UTF-8 snapcraft']' returned non-zero exit status 1
```

**Comment by kyrofa** [comment]
Yeah you need to build it with optimizations: CFLAGS="-O2" (like the apache plugin does).

**Comment by oparoz** [comment]
Is the default in Ubuntu O3?
